In [1]:
import katdal
import numpy as np
import pickle

In [2]:
np.set_printoptions(precision=1,suppress=True)

In [3]:
def target(h):
    h.catalogue.remove('Nothing')
    if len(h.catalogue) >0 :
        tgt=str(h.catalogue.targets[0])[0:12]
    else:
        tgt="Nothing:Bad DATA"
    return tgt

In [4]:
def get_ants(h):
    a_list=[]
    aa=h.file['TelescopeState']['cal_antlist']
    for i,ai in enumerate(aa):
        a_list.append(pickle.loads(ai[1]))
    a_array=np.array(a_list)
    labels=a_array[0]
    return labels

In [5]:
def phases(h):
    g = h.file['TelescopeState']['cal_product_G']
    g_list = []
    for i, gi in enumerate(g):
        g_list.append(pickle.loads(gi[1]))
    g_array = np.array(g_list)
    HH=g_array[:,0,:]
    VV=g_array[:,1,:]
    HHbefore=np.rad2deg(np.angle(HH)[0])
    HHafter=np.rad2deg(np.angle(HH)[-1])
    VVbefore=np.rad2deg(np.angle(VV)[0])
    VVafter=np.rad2deg(np.angle(VV)[-1])
    return HHbefore, HHafter,VVbefore,VVafter

In [6]:
files=['/var/kat/archive2/data/MeerKATAR1/telescope_products/2016/12/21/1482329065.h5',\
      '/var/kat/archive2/data/MeerKATAR1/telescope_products/2016/12/21/1482330032.h5',\
      '/var/kat/archive2/data/MeerKATAR1/telescope_products/2016/12/21/1482359330.h5',\
      '/var/kat/archive2/data/MeerKATAR1/telescope_products/2016/12/22/1482393086.h5']

In [7]:
for f in files:
    h=katdal.open(f)
    p=phases(h)
    print f[-13:-3], target(h)
    print get_ants(h)
    print p[0],"\n",p[1],"\n\n",p[2],"\n",p[3]
    

1482329065 PKS 1934-63 
['m003' 'm006' 'm008' 'm010' 'm014' 'm015' 'm021' 'm022' 'm025' 'm031'
 'm062' 'm063']
[ 4.   4.5  7.8  7.3  7.5  8.3  9.   7.8 -0.   3.6  8.8  7.1] 
[ 18.   15.9  18.9  17.6  10.   16.1  15.3  15.    0.    5.2   7.7  19.2] 

[ 10.6   9.7   6.8   4.4   9.9   9.5  15.4  10.1   0.    3.9   8.8  11.3] 
[ 19.6  14.4  24.6  -0.3  14.8   5.9  14.   37.7  -0.    3.8 -10.8  -8.5]
1482330032 PKS 1934-63 
['m003' 'm006' 'm008' 'm010' 'm014' 'm015' 'm021' 'm022' 'm025' 'm031'
 'm062' 'm063']
[ 4.   4.5  7.8  7.3  7.5  8.3  9.   7.8 -0.   3.6  8.8  7.1] 
[  90.    59.7  136.4   75.1  148.3   75.   122.    72.9   -0.    -8.6
  112.    74.8] 

[ 10.6   9.7   6.8   4.4   9.9   9.5  15.4  10.1   0.    3.9   8.8  11.3] 
[ 127.8   41.8  107.2   87.9   83.5   56.5  104.8   52.9   -0.    43.3
   51.6   84.3]
1482359330 PKS 0408-65 
['m003' 'm006' 'm008' 'm010' 'm014' 'm015' 'm021' 'm022' 'm025' 'm031'
 'm062' 'm063']
[ 4.   4.5  7.8  7.3  7.5  8.3  9.   7.8 -0.   3.6  8.8  7.1] 
[ 