In [15]:
import katdal
import numpy as np
import pickle

In [16]:
import time

In [17]:
np.set_printoptions(precision=1,suppress=True)

In [18]:
def target(h):
    h.catalogue.remove('Nothing')
    if len(h.catalogue) >0 :
        tgt=str(h.catalogue.targets[0])[0:12]
    else:
        tgt="Nothing:Bad DATA"
    return tgt

In [19]:
def get_ut(f):
    nn=int(f[-13:-3])
    print nn
    ut=time.asctime(time.gmtime(nn))
    return ut

In [20]:
def get_ants(h):
    a_list=[]
    aa=h.file['TelescopeState']['cal_antlist']
    for i,ai in enumerate(aa):
        a_list.append(pickle.loads(ai[1]))
    a_array=np.array(a_list)
    labels=a_array[0]
    return labels

In [21]:
def phases(h):
    g = h.file['TelescopeState']['cal_product_G']
    g_list = []
    for i, gi in enumerate(g):
        g_list.append(pickle.loads(gi[1]))
    g_array = np.array(g_list)
    HH=g_array[:,0,:]
    VV=g_array[:,1,:]
    HHbefore=np.rad2deg(np.angle(HH)[0])
    HHafter=np.rad2deg(np.angle(HH)[-1])
    VVbefore=np.rad2deg(np.angle(VV)[0])
    VVafter=np.rad2deg(np.angle(VV)[-1])
    return HHbefore, HHafter,VVbefore,VVafter

In [22]:
files=['/var/kat/archive2/data/MeerKATAR1/telescope_products/2016/12/05/1480951380.h5',\
      '/var/kat/archive2/data/MeerKATAR1/telescope_products/2016/12/05/1480952018.h5',\
      '/var/kat/archive2/data/MeerKATAR1/telescope_products/2016/12/05/1480952745.h5',\
      '/var/kat/archive2/data/MeerKATAR1/telescope_products/2016/12/05/1480964718.h5',
      '/var/kat/archive2/data/MeerKATAR1/telescope_products/2016/12/05/1480977085.h5']

In [23]:
for f in files:
    h=katdal.open(f)
    p=phases(h)
    print get_ut(f),f[-13:-3], target(h)
    print get_ants(h)
    print p[0],"\n",p[1],"\n\n",p[2],"\n",p[3]
    

1480951380
Mon Dec  5 15:23:00 2016 1480951380 PKS 1934-63 
['m006' 'm007' 'm008' 'm010' 'm014' 'm015' 'm025' 'm031' 'm062' 'm063']
[   8.8  -21.3    3.4    0.    10.9  -42.1 -104.9  -97.9  -16.7  -33.2] 
[   8.8  -21.2    3.2    0.    10.4  -42.2 -104.9  -98.   -16.8  -33.3] 

[  32.6   24.9   26.8    0.   -84.9 -122.5 -170.5  171.4 -152.8  -80.3] 
[  32.7   25.    26.9   -0.   -85.3 -122.5 -170.5  171.4 -152.8  -80.3]
1480952018
Mon Dec  5 15:33:38 2016 1480952018 PKS 1934-63 
['m006' 'm007' 'm008' 'm010' 'm014' 'm015' 'm025' 'm031' 'm062' 'm063']
[   8.8  -21.3    3.4    0.    10.9  -42.1 -104.9  -97.9  -16.7  -33.2] 
[-15.9 -20.6   6.8   0.   48.3  12.2 -61.7 -49.9  44.8  33. ] 

[  32.6   24.9   26.8    0.   -84.9 -122.5 -170.5  171.4 -152.8  -80.3] 
[  27.7   33.3   28.6    0.   -27.8  -64.8 -111.6  -46.9   26.4   11.3]
1480952745
Mon Dec  5 15:45:45 2016 1480952745 PKS 1934-63 
['m006' 'm007' 'm008' 'm010' 'm014' 'm015' 'm025' 'm031' 'm062' 'm063']
[   8.8  -21.3    3.4    0.   